version: '3'
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./conf.d:/etc/mysql/conf.d
      - ./datadir:/var/lib/mysql
